### ISSUE TITLE
Dublicate content types

### ISSUE THREAD

**Issue by jp5525** [fridge-cms/issues#2]
If you try to add an new content type with the same name as an already existing content type a new entry in the menu will be added that links to the same content type, but there is no obvious way to remove it.

**Comment by tamagokun** [comment]
This should be fixed in the API now, you'll get an error if you try to make a content type with the same slug. Do you need help removing the duplicate?

**Comment by jp5525** [comment]
Awesome thanks,
No James was able to remove it.

**Comment by tamagokun** [comment]
Sweet, let me know if this is still an issue.
